WORK_ROOT: "/home/oahmed6/scr16_blangme2/oahmed/delta_exp2"
REPO_DIRECTORY: "/home/oahmed6/genome_info_curve"
RINDEX_BUILD_DIRECTORY: "/home/oahmed6/r-index_dev/build"
LZ77_BUILD_DIRECTORY: "/home/oahmed6/PFP_LZ77/build"